# Generated by Django 3.2.16 on 2022-11-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiteWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout', models.CharField(max_length=50)),
                ('approach', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MediumWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('workout', models.CharField(max_length=50)),
            ],
        ),
    ]
