# Generated by Django 3.2.16 on 2022-11-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout', models.CharField(max_length=50)),
                ('approach', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout', models.CharField(max_length=50)),
                ('approach', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='LiteWork',
        ),
        migrations.DeleteModel(
            name='MediumWork',
        ),
    ]
